### ISSUE TITLE
Group Milestone - Implementation (Sprint 2) complete

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#127]
core flows are in the REAME.me
![demo_wwcodeapp_take_2](https://cloud.githubusercontent.com/assets/1654151/10802450/2e76131e-7d7a-11e5-874b-0f0e12257d64.gif)

**Comment by zassmin** [comment]
The gradient on the gif looks off, that's not how it actually appears.

**Comment by zassmin** [comment]
our milestone is: 
https://github.com/WomenWhoCode/WomenWhoCode/issues?q=milestone%3A%22Sprint+2%22+is%3Aclosed

Most stories/flow are also outlined in the readme. 

fyi @RoyPuja @shehbashahab

/cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Nice work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.

* Good job creating and achieving your [milestones](https://github.com/WomenWhoCode/WomenWhoCode/issues?q=milestone%3A%22Sprint+2%22+is%3Aclosed) for sprint 2
* Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place. 
* Good to see you have tasks/issues being worked on actively. Please consider regularly updating your readme file so you have a better idea of what's left to do.
* Try to challenge yourself on the UI/visual side of things in the coming days. Not necessarily flashy things, but it's the small details that take a lot of work.
* Keep working on integrating the core flows and make sure all pieces fit together perfectly.
* Consult with your mentors to get their feedback as often as you can. Remember they are here to help!
* While working on polishing your app for next sprint, remember that your app follows the [android design guidelines] (http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns] (http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
