### ISSUE TITLE
Timeline Activity

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#21]
* pre-pop according to user's interests, profile details and basic wwcode stuff
* subscribe user to any feature that is set to feature.is_auto_subscribe?() true, based on modeling from issue #8 
* this activity will render a tab layout like using pager slider lib: http://guides.codepath.com/android/Sliding-Tabs-with-PagerSlidingTabStrip
* the pager will instantiate the: `new UserTimelineFragment`, `new FeaturesTimelineFragment`, `new EventsTimelineFragment`
* xml will be a basic list view with relative layout, maybe call it `fragments_timeline_list.xml` and a corresponding `item_view.xml`
* details of specific fragments are going to be listed in their own issues: #18 #23 #20 

![screen shot 2015-10-14 at 5 06 59 pm](https://cloud.githubusercontent.com/assets/1654151/10526848/113cca8c-7342-11e5-8e78-fb5ac2711b27.png)

**Comment by shehbashahab** [comment]
closed by https://github.com/WomenWhoCode/WomenWhoCode/pull/39
