### ISSUE TITLE
Features Detail View

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#22]
* here a user will see feature title, image, subscribe button if they are not subscribed and description
* there should be a back/up arrow at the top navigation to take the back to the features timeline fragment https://guides.codepath.com/android/Extended-ActionBar-Guide#navigating-up-with-the-app-icon

**mock might change
<img width="253" alt="screen shot 2015-10-15 at 1 50 51 pm" src="https://cloud.githubusercontent.com/assets/1654151/10527150/cef8336c-7343-11e5-96c6-c6ae073d7ca1.png">

**Comment by shehbashahab** [comment]
closed by #52
