### ISSUE TITLE
posts: when a user adds a new post, scroll to the that new post on the list

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#279]
* this requires passing the post back to the postlist fragment
* this requires telling the view where to go

**Comment by zassmin** [comment]
@RoyPuja noticing you are assigned. Are you actively working on this?

**Comment by RoyPuja** [comment]
Yes,I am.

**Comment by RoyPuja** [comment]
This works for text posts.@zassmin,@shehbashahab Can one of you verify it for image posts?I cannot check on my phone.

**Comment by RoyPuja** [comment]
Checked for the post with picture.
