### ISSUE TITLE
Homework #5

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#3]
The readme includes stories and will include mocks in a few seconds. cc: @codepathreview @codepath

**Comment by RoyPuja** [comment]
![screen shot 2015-10-14 at 3 57 33 pm](https://cloud.githubusercontent.com/assets/11285573/10502938/0d96c6f4-72a6-11e5-9be4-80f4f2c4fdbd.png)
![screen shot 2015-10-14 at 5 07 17 pm](https://cloud.githubusercontent.com/assets/11285573/10502937/0d966f7e-72a6-11e5-87b3-e8600803b29f.png)
![screen shot 2015-10-14 at 5 07 09 pm](https://cloud.githubusercontent.com/assets/11285573/10502939/0da8f612-72a6-11e5-8b3d-dafc4967030a.png)
![screen shot 2015-10-14 at 5 06 59 pm](https://cloud.githubusercontent.com/assets/11285573/10502940/0da96750-72a6-11e5-90e1-8e61465cdf68.png)

**Comment by shehbashahab** [comment]
<img width="705" alt="screen shot 2015-10-14 at 7 03 30 pm" src="https://cloud.githubusercontent.com/assets/3621826/10502999/af2c17b2-72a6-11e5-8a82-a13be5460f7a.png">
<img width="686" alt="screen shot 2015-10-14 at 7 03 38 pm" src="https://cloud.githubusercontent.com/assets/3621826/10502998/af2a6160-72a6-11e5-8f82-f818c3e41aba.png">

**Comment by nesquena** [comment]
Thanks for submitting this and documenting your progress so far! Good to see you have an initial version of the wireframes complete as a starting point for your app.

Remember that by the end of your second sprint, we expect each team to have their core flows functionally complete (but rough) so this week your team should complete the first 50% of your core functionality.

While building this app, try to keep in your mind the story for your app and what you need to have a polished demo. Be aggressive about which features you can scope into the first version for internal demo day. Excited to see what your group comes up with! Let us know what we can do to help.
