### ISSUE TITLE
Add details on how to contribute on README

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#326]

**Comment by chhavip** [comment]
@zassmin Hello, I am Chhavi Gupta, an engineering student and member of WWC Delhi team. I saw the project and am interested in contributing to it. Can I get started by completing this issue?

**Comment by zassmin** [comment]
@chhavip :+1: looking forward to seeing your PR! Feel free to remove the member stories section entirely since it's reflected in our issues and milestones.
