### ISSUE TITLE
Remove chat fragments and pagerview from Events and Topics

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#330]
EventChatFragment
TopicChatFragment

**Comment by jig08** [comment]
@zassmin Removing `EventChatFragment` and `TopicChatFragment` would be easy, but may I inquire about where do we plan to move the **chat** functionality then ? Or would we be removing it all together ?

**Comment by zassmin** [comment]
@jig08 great question. It brings up the point about where the the UI/UX for the app is headed, which isn't described anywhere in this repository. It's important information to have to give people more context and I've considered adding it to the wiki. Happy to hear your thoughts. 

The short answer is that for our initial Beta push for this app, we decided to shift focus less on group chat and more on 1:1 chat between people. This decision was mostly because based on user feedback; it was confusing to the user when to post and when to chat for a given topic/event. We for now, will instead enhance the post functionality, by being able to reply to posts.

**Comment by jig08** [comment]
@zassmin Gotcha !
Thank you for elaborating :)

**Comment by zassmin** [comment]
reopened since the chat fragments still needs to be removed: 
https://github.com/WomenWhoCode/WomenWhoCode/blob/master/app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventChatFragment.java
https://github.com/WomenWhoCode/WomenWhoCode/blob/master/app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeatureChatFragment.java

**Comment by zassmin** [comment]
@shehbashahab lightening fast :zap: :facepunch:
