### ISSUE TITLE
Remove unused strings, vars and functions

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#331]

**Comment by shehbashahab** [comment]
closed by #336

**Comment by shehbashahab** [comment]
@jig08 there are still some unused imports and variables, can you take care of this?

**Comment by jig08** [comment]
@shehbashahab Yes, shall look into it.

**Comment by zassmin** [comment]
@shehbashahab or @jig08 is there ready to close?

**Comment by shehbashahab** [comment]
@zassmin and @jig08 I still see 139 unused declarations that need review. Some might be valid getters/setters and the lint warning can be ignored. @jig08 are you working on these otherwise I can take them on.
