### ISSUE TITLE
Extract hard-coded text to Strings resource

### ISSUE THREAD

**Issue by shehbashahab** [WomenWhoCode/WomenWhoCode#337]

**Comment by jig08** [comment]
@shehbashahab I would like to work on this :)

**Comment by shehbashahab** [comment]
@jig08 go for it!

**Comment by shehbashahab** [comment]
@jig08 was this ready for review? There is a build failure due to <string name="review_msg">We'll review and get back to you soon enough!</string>:  Error:(435) Apostrophe not preceded by \ (in We'll review and get back to you soon enough!)

**Comment by jig08** [comment]
@shehbashahab Shall rectify it .

**Comment by zassmin** [comment]
@shehbashahab or @jig08 is this ready to close?

**Comment by shehbashahab** [comment]
@zassmin and @jig08 I still see 60 outstanding uses of hardcoded strings. @jig08 are you working on these?
