### ISSUE TITLE
transition Toasts to Snackbars

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#355]
Per material design, snackbars are a best practice. Toasts are best used for debug purposes now a days.

**Comment by opticod** [comment]
I am new here..I want to start contributing... 
should i change the commented toast codes or only the not commented one ?

**Comment by opticod** [comment]
should i change all into snackbars? @zassmin

**Comment by zassmin** [comment]
@opticod welcome! Yes, the gotcha is that if it smells like a toast only meant for debugging or if it's commented out, just ignore. There is another issue https://github.com/WomenWhoCode/WomenWhoCode/issues/356 out to get them removed. In my quick search, it looks like there may only be one area where Toasts needs transitioning to a Snackbar here: https://github.com/WomenWhoCode/WomenWhoCode/blob/f9665981cc6b193226d25a2284850135772f0f10/app/src/main/java/com/example/womenwhocode/womenwhocode/activities/SignUpEmailActivity.java#L80-L85

Definitely use your best judgement.

**Comment by opticod** [comment]
Thanks @zassmin for helping.

**Comment by zassmin** [comment]
closed by #358
