### ISSUE TITLE
delete any pointless Toasts

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#356]
Some pointless ones are already commented out other may not be.

By pointless information, I mean information that doesn't tell the user a next step, a notice, reminder.

**Comment by chhavip** [comment]
Will Do.

**Comment by shehbashahab** [comment]
Not seeing any remaining Toasts in the code. Can this be closed?

**Comment by zassmin** [comment]
@shehbashahab :+1:
