### ISSUE TITLE
[README] add a list of opensource technologies used section

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#360]
For example: https://github.com/zassmin/MySimpleTweets, reference header Open-source libraries used

**Comment by jig08** [comment]
@zassmin I would like to work on this :)

**Comment by zassmin** [comment]
@jig08 :tada:

**Comment by chhavip** [comment]
@zassmin , is this done or requires work? Could do this.

**Comment by zassmin** [comment]
@chhavip :+1:

**Comment by chhavip** [comment]
Fixed by #422
