### ISSUE TITLE
[PERSONALIZATION FLOW] When you unclick a check box, the color currently stays teal, it should go back to the grey

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#365]
There is a comment explaining the issue, https://github.com/WomenWhoCode/WomenWhoCode/blob/master/app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java#L88-L89. 

Issue #361 should be able to solve. I'm making this a separate issue to track the bug independently even if it's resolved with the same code changes from #361 .

**Comment by shehbashahab** [comment]
@opticod This checkin triggered some lint warnings, can you please resolve them? Thank you!

Unused resources (please delete these if you do not plan to use them):
The resource 'R.drawable.btn_check_off_focused' appears to be unused
The resource 'R.drawable.btn_check_on_focused' appears to be unused
The resource 'R.drawable.btn_check_to_off_mtrl_000' appears to be unused
The resource 'R.color.checkbox' appears to be unused

Duplicated icons under different names (please consolidate dups)
The following unrelated icon files have identical contents: btn_check_off.png, btn_check_off_focused.png
The following unrelated icon files have identical contents: btn_check_off_disabled.png, btn_check_off_disabled_focused.png
The following unrelated icon files have identical contents: btn_check_off_disabled.png, btn_check_off_disabled_focused.png
The following unrelated icon files have identical contents: btn_check_off.png, btn_check_off_focused.png
The following unrelated icon files have identical contents: btn_check_on.png, on_15.png
The following unrelated icon files have identical contents: btn_check_on_disabled.png, btn_check_on_disabled_focused.png
The following unrelated icon files have identical contents: btn_check_on_disabled.png, btn_check_on_disabled_focused.png
The following unrelated icon files have identical contents: btn_check_on.png, on_15.png

**Comment by opticod** [comment]
@shehbashahab I am done with refactoring. But i was unable to duplicate the tint warning .Can you provide me the log ?

**Comment by shehbashahab** [comment]
@opticod Steps to replicate:

1. Verify you have the latest code from master
2. Analyze -> Inspect Code -> Inspection Scope (Whole Project)
3. Under Android Lint, you will notice 3 new warnings:
* Duplicated icons under different names
* Unused resources 
* Image defined in density-independent drawable folder

Note for 'Image defined in density-independent drawable folder' warning, you only need to fix the ones related to your checkin.


There is an additional warning

**Comment by opticod** [comment]
@shehbashahab in 100d352 warning 1 ,2 are resolved, and 3 can be resolved by either placing the drawable files of checkboxes in drawable-nodpi folder or providing ldpi,mdpi, hdpi assets and deleting them from drawables. Providing some extra assets(30 animating +3 check box each) for ldpi,mdpi,hdpi for animating icons will definitley increase the look in higher dpi devices.

(or we can do what @zassmin had suggested for later,using .9.png )

Please let me know ,which will be best suitable for this project. Thank You

**Comment by shehbashahab** [comment]
@opticod Agree with @zassmin on using 9 patch drawables. Will open a separate issue to tackle all of these in the future.

Please leave this issue open until 100d352 is pulled into master so we remember to verify that the first 2 lint warnings have been resolved during our code review. Thanks!

**Comment by shehbashahab** [comment]
Closed by #381
