### ISSUE TITLE
rename package from com.example.womenwhocode.womenwhocode to com.womenwhocode.womenwhocode

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#385]
In order to put the app in the google play store, the package must be renamed.

Requirements:
* Please do a safe rename to ensure each dependency has the newly named package name.
* Please go through the entire app flow to ensure nothing broke as a result, before submitting a PR.

**Comment by opticod** [comment]
I will work on this @zassmin

**Comment by opticod** [comment]
done @zassmin
