### ISSUE TITLE
Show Error Messages on failed Login|Register

### ISSUE THREAD

**Issue by chhavip** [WomenWhoCode/WomenWhoCode#408]
Currently if a login or register fails due to duplicate id or incorrect password, no error is displayed, a toast message with corresponding parse error will be beneficial for the user to gather that their attempt has failed and be able to try again. @zassmin

**Comment by chhavip** [comment]
@zassmin , does this require work?

**Comment by zassmin** [comment]
@chhavip something similar to the [SignUpEmailActivity](https://github.com/WomenWhoCode/WomenWhoCode/blob/master/app/src/main/java/com/womenwhocode/womenwhocode/activities/SignUpEmailActivity.java#L74-L79) could work!
