### ISSUE TITLE
Settle on a official open source license and add it to the readme 

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#413]
These are all the official open source licenses: 
* https://opensource.org

Goals: 
We want to have our code be officially open sourced but want a way to say the trademark and copyright is Women Who Code's. We would also love it if we knew other orgs were adopting our code for good.

**Comment by ogormans** [comment]
Completed a full review of the following licenses:

* Apache License 2.0
* BSD 3-Clause "New" or "Revised" license
* BSD 2-Clause "Simplified" or "FreeBSD" license
* GNU General Public License (GPL)
* GNU Library or "Lesser" General Public License (LGPL)
* MIT license
* Mozilla Public License 2.0
* The Non-Profit Open Software License version 3.0 (NPOSL-3.0)
* Common Development and Distribution License
* Eclipse Public License

Our top choices after review were:
1. The Non-Profit Open Software License version 3.0 (NPOSL-3.0)
2. Common Development and Distribution License
3. GNU General Public License, version 3 (GPL-3.0)

Our final choice after review is:
[The Non-Profit Open Software License version 3.0 (NPOSL-3.0)](https://opensource.org/licenses/NPOSL-3.0)

Reasons for choosing NPOSL 3.0:
* Designed for Non-Profits
* Acceptable language and terms for trademarks and attribution
* Clear wording
