### ISSUE TITLE
[Create Profile] Add ripple effect

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#417]

**Comment by chhavip** [comment]
@zassmin , which are the activities pointed by create profile| view profile as the profile link is empty for now?

**Comment by zassmin** [comment]
I updated the issue to only reflect create profile. It's in the [UserProfileActivity](https://github.com/WomenWhoCode/WomenWhoCode/blob/master/app/src/main/java/com/womenwhocode/womenwhocode/activities/UserProfileActivity.java), which is where the user is taken after successful sign up.
