### ISSUE TITLE
Add string constants to strings.xml 

### ISSUE THREAD

**Issue by hkasera** [WomenWhoCode/WomenWhoCode#433]
Over here in [`EventDetailsActivity.java`](https://github.com/WomenWhoCode/WomenWhoCode/blob/94b93daf99b6fa1b718380935e7be03376c15d24/app/src/main/java/com/womenwhocode/womenwhocode/activities/EventDetailsActivity.java#L46) and [`FeatureDetailsActivity.java`](https://github.com/WomenWhoCode/WomenWhoCode/blob/94b93daf99b6fa1b718380935e7be03376c15d24/app/src/main/java/com/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java#L52), I notice that we have used string constants in code. I think it is good to add them in `strings.xml` so that the same string is not declared in multiple activities. This will also help later when we want to support multiple languages.

If this is a welcome contribution, I would like to send a PR for this.

Thanks,
Harshita

**Comment by shehbashahab** [comment]
@hkasera Yes please

**Comment by hkasera** [comment]
@shehbashahab Sure, I will start working on the PR. Thanks!

**Comment by jig08** [comment]
@hkasera Any updates on this ?
