### ISSUE TITLE
Incorrect Snackbar Message On No Internet Connectivity during Signup

### ISSUE THREAD

**Issue by harshitagupta30** [WomenWhoCode/WomenWhoCode#438]
When we are not connected to the internet during the process of signup then as a feedback a message appear at the bottom of the screen stating "Something went wrong.Try Again? Thanks! " which doesn't tell the user that there is no internet connectivity and the internet needs to be turned on.

**Comment by harshitagupta30** [comment]
I am currently working on this issue and soon I'll send the PR regarding the same.

**Comment by harshitagupta30** [comment]
That thing is there inside the code but due to lag one can't identify it at a glance.

**Comment by jig08** [comment]
@harshitagupta30 
Thanks for your input. 
May I know why did you close the issue if you felt the it still persists ? 😃

**Comment by harshitagupta30** [comment]
Hi. The reason behind closing this issue is because initially when I open
the app an incorrect message was appearing but after checking out and
debugging the code I just found that issue was due to time lag. Proper
message regarding the Internet connection is being displayed. :)

**Comment by jig08** [comment]
Cool 👍
