### ISSUE TITLE
Review Profile - round 2

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#56]
This is page we take the user to complete the user profile
Profile: 
* full name
* job title
* github_id (if one exists)
* image_url
  * make it so the user can take a photo
* location
* network
The profile model will be created in issue #16

The network list in the form will be `Network.getAll()` on Network model. Default will be "" - blank.

<img width="246" alt="screen shot 2015-10-15 at 12 18 27 pm" src="https://cloud.githubusercontent.com/assets/1654151/10524924/def7666e-7336-11e5-8e9c-5578f2ec70ac.png">

**Comment by RoyPuja** [comment]
Need to insert code to save location.

**Comment by RoyPuja** [comment]
User profile information 
full name
job title
github_id (if one exists)---not yet implemented
image_url--not yet implemented
make it so the user can take a photo--not yet implemented
location---Zassmin to update
network The profile model will be created in issue #16

**Comment by zassmin** [comment]
update: 
don't worry about - github_id (if one exists)---not yet implemented
