### ISSUE TITLE
sign up form Part 2

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#57]
ask for user's username, not full name

* note parse requires a username field - that's the only reason we have it
* form should include username
<img width="219" alt="screen shot 2015-10-15 at 12 10 15 pm" src="https://cloud.githubusercontent.com/assets/1654151/10524712/d6051d2c-7335-11e5-9664-82a9454bcdde.png">

**Comment by RoyPuja** [comment]
Fixed.
