### ISSUE TITLE
Login (Via Email): Add validations preventing bad user entry

### ISSUE THREAD

**Issue by shehbashahab** [WomenWhoCode/WomenWhoCode#70]
Login via email:
1. If username or password are empty, then disable login button
2. If e-mail address is invalid, then throw error
3. If password is too short throw error

**Comment by chhavip** [comment]
@shehbashahab  Is this resolved? Would take it up.

**Comment by zassmin** [comment]
@RoyPuja are you going to work on this? @chhavip is interested in picking this up!

**Comment by RoyPuja** [comment]
@chhavip You can take it up. I am not working on this.

**Comment by chhavip** [comment]
Okay!

**Comment by chhavip** [comment]
@zassmin , this issue can be closed now I guess.
